/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DIAGNOSTICS_GATEWAY_HEALTH_PB_H_INCLUDED
#define PB_DIAGNOSTICS_GATEWAY_HEALTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Esquema de salud y estado del Gateway (ESP32-P4)
 Publicado de forma independiente a la telemetría de los nodos. */
typedef struct _diagnostics_GatewayHealthEvent {
    /* Identity */
    char gateway_id[32]; /* MAC del ESP32-P4 (ej. "gateway-AA:BB:CC:DD:EE:FF") */
    /* Status */
    bool is_degraded_mode; /* True si la MicroSD ha fallado o fue extraída */
    /* MicroSD / Storage Diagnostics */
    bool sd_card_mounted; /* Estado físico del montaje VFS */
    uint32_t sd_card_total_mb;
    uint32_t sd_card_free_mb;
    uint32_t sd_io_errors; /* Contador acumulado de errores I/O */
    /* Uptime & System */
    uint32_t uptime_seconds;
    uint32_t free_heap_bytes;
    /* Event Trigger */
    char alert_message[128]; /* Opcional: Mensaje crítico para operadores */
} diagnostics_GatewayHealthEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define diagnostics_GatewayHealthEvent_init_default {"", 0, 0, 0, 0, 0, 0, 0, ""}
#define diagnostics_GatewayHealthEvent_init_zero {"", 0, 0, 0, 0, 0, 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define diagnostics_GatewayHealthEvent_gateway_id_tag 1
#define diagnostics_GatewayHealthEvent_is_degraded_mode_tag 2
#define diagnostics_GatewayHealthEvent_sd_card_mounted_tag 3
#define diagnostics_GatewayHealthEvent_sd_card_total_mb_tag 4
#define diagnostics_GatewayHealthEvent_sd_card_free_mb_tag 5
#define diagnostics_GatewayHealthEvent_sd_io_errors_tag 6
#define diagnostics_GatewayHealthEvent_uptime_seconds_tag 7
#define diagnostics_GatewayHealthEvent_free_heap_bytes_tag 8
#define diagnostics_GatewayHealthEvent_alert_message_tag 9

/* Struct field encoding specification for nanopb */
#define diagnostics_GatewayHealthEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   gateway_id,        1) \
X(a, STATIC,   SINGULAR, BOOL,     is_degraded_mode,   2) \
X(a, STATIC,   SINGULAR, BOOL,     sd_card_mounted,   3) \
X(a, STATIC,   SINGULAR, UINT32,   sd_card_total_mb,   4) \
X(a, STATIC,   SINGULAR, UINT32,   sd_card_free_mb,   5) \
X(a, STATIC,   SINGULAR, UINT32,   sd_io_errors,      6) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_seconds,    7) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap_bytes,   8) \
X(a, STATIC,   SINGULAR, STRING,   alert_message,     9)
#define diagnostics_GatewayHealthEvent_CALLBACK NULL
#define diagnostics_GatewayHealthEvent_DEFAULT NULL

extern const pb_msgdesc_t diagnostics_GatewayHealthEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define diagnostics_GatewayHealthEvent_fields &diagnostics_GatewayHealthEvent_msg

/* Maximum encoded size of messages (where known) */
#define DIAGNOSTICS_GATEWAY_HEALTH_PB_H_MAX_SIZE diagnostics_GatewayHealthEvent_size
#define diagnostics_GatewayHealthEvent_size      197

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
