/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "gateway_health.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(diagnostics_GatewayHealthEvent, diagnostics_GatewayHealthEvent, AUTO)
